version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  azure-cli: circleci/azure-cli@1.0.0

jobs:
  build:
    docker:
      - image: 'citus/extbuilder:latest'
    steps:
      - checkout
      - run:
          name: 'Configure, Build, and Install'
          command: build-ext
      - persist_to_workspace:
          root: .
          paths: [.]
  check-style:
    docker:
      - image: 'citusdata/stylechecker:latest'
    steps:
      - checkout
      - run:
          name: 'Check Style'
          command: citus_indent --check
      - run:
          name: 'Fix whitespace'
          command: ci/editorconfig.sh
      - run:
          name: 'Check if whitespace fixing changed anything, install editorconfig if it did'
          command: git diff --exit-code
      - run:
          name: 'Remove useless declarations'
          command: ci/remove_useless_declarations.sh
      - run:
          name: 'Check if changed'
          command: git diff --cached --exit-code
      - run:
          name: 'Normalize test output'
          command: ci/normalize_expected.sh
      - run:
          name: 'Check if changed'
          command: git diff --exit-code
      - run:
          name: 'Check for banned C API usage'
          command: ci/banned.h.sh
  check-sql-snapshots:
    docker:
      - image: 'citus/extbuilder:latest'
    steps:
      - checkout
      - run:
          name: 'Check Snapshots'
          command: "./configure && make check-sql-snapshots -C src/backend/distributed"
  multi1:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'
  multi2:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'
  multi3:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'

  multi20:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'

  multi19:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'

  multi18:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'

  multi17:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'

  multi16:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'

  multi15:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'

  multi14:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'

  multi13:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'

  multi12:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'

  multi11:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'

  multi10:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'

  multi9:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'

  multi8:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'

  multi7:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'

  multi6:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'

  multi5:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'

  multi4:
    docker:
      - image: 'citus/exttester-12:latest'
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Install and Test (check-multi)'
          command: 'chown -R circleci:circleci /home/circleci && install-and-test-ext check-multi'
          no_output_timeout: 2m
      - codecov/upload:
          flags: 'test_12,multi'


workflows:
  version: 2
  build_and_test:
    jobs:
      - build

      - multi1:
          requires: [build]
      - multi20:
          requires: [build]
      - multi19:
          requires: [build]
      - multi18:
          requires: [build]
      - multi17:
          requires: [build]
      - multi16:
          requires: [build]
      - multi15:
          requires: [build]
      - multi14:
          requires: [build]
      - multi13:
          requires: [build]
      - multi12:
          requires: [build]
      - multi11:
          requires: [build]
      - multi10:
          requires: [build]
      - multi9:
          requires: [build]
      - multi8:
          requires: [build]
      - multi7:
          requires: [build]
      - multi6:
          requires: [build]
      - multi5:
          requires: [build]
      - multi4:
          requires: [build]
      - multi3:
          requires: [build]
      - multi2:
          requires: [build]
